name: GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 2

      - name: Set up pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Set up Node
        uses: actions/setup-node@v4.0.3
        with:
          cache: pnpm
          node-version-file: ".nvmrc"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.17

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: bun run build 

      - name: GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Make sure this matches your Vite output directory
